access_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmZhbiIsImV4cCI6MTcxNzE3NTc3MX0.RK-8tx7aJDm7iVTb5X0aFNv8F6rf9nduYDA_Zg53uEY"

### Create User
POST http://localhost:8000/create_user/
Content-Type: application/json

{
  "username": "newuser3",
  "email": "newuser3@example.com",
  "password": "newpassword"
}

### Get Token
POST http://localhost:8000/token
Content-Type: application/x-www-form-urlencoded

username=irfan&password=abc123

### Get Current User Info
GET http://localhost:8000/user/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmZhbiIsImV4cCI6MTcxNzMzODcyOX0.5K1rdm705xCJatHBRf9FkRgyni2MAGan2ByW6ZvOT3o


### Create Security Test Case
POST http://localhost:8000/security/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmZhbiIsImV4cCI6MTcxNzMzODcyOX0.5K1rdm705xCJatHBRf9FkRgyni2MAGan2ByW6ZvOT3o

{
  "name": "SQL Injection 5",
  "description": "Test for SQL Injection vulnerability",
  "payload": "'"
}

### Get Security Test Cases
GET http://localhost:8000/security_test_cases/
Authorization: Bearer 

### Get Security Test Case
GET http://localhost:8000/security/security_test_cases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmZhbiIsImV4cCI6MTcxNzMxNTU2Mn0.2TTr9Y_fmtZ50zFR8FVrDq_jqwaZ_LH5xg3kpbxNCGY

### Get Token Verification
GET http://localhost:8000/token/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmZhbiIsImV4cCI6MTcxNzMwOTUwMn0.mUdYc_OgaHRMmyli-HAbFQ_iMBJ87NKSjKikULEqyVg

### Testing VamPI API
GET http://localhost:5000/users/v1/'


### Using security_test/sqli/ to test VamPI API
POST http://localhost:8000/security/runTest/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmZhbiIsImV4cCI6MTcxNzM0NTUxN30.CfbGxOC8kM_bfFeXV4D2UpwWZRTbw054LATla4DT_Jg

{
  "url": "http://localhost:5000/users/v1/",
  "id": "14"
}
